In [11]:
import pandas as pd
import plotly.graph_objects as go

# Set the season to analyse
# Replace 'XXX' with the season_id you want to target, e.g. 'f010783f-7fb5-40d8-9e00-6d8a45fa448e'
target_season_id = 'f010783f-7fb5-40d8-9e00-6d8a45fa448e'

# Load data
game_week_scores = pd.read_csv('../CSV/24.09.2026/game_week_scores_rows.csv')
game_weeks = pd.read_csv('../CSV/24.09.2026/game_weeks_rows.csv')
season_players = pd.read_csv('../CSV/24.09.2026/season_players_rows.csv')
profiles = pd.read_csv('../CSV/24.09.2026/profiles_rows.csv')

if target_season_id == 'XXX':
    raise ValueError(
        "Set target_season_id to the season_id you want to analyse before running the notebook."
    )

# Restrict to the selected season and only players in that season
active_player_ids = season_players.loc[
    season_players['season_id'] == target_season_id,
    'player_id'
].unique()

target_game_weeks = game_weeks.loc[
    game_weeks['season_id'] == target_season_id,
    ['id', 'week_number']
]

# Merge data
merged = (
    game_week_scores[game_week_scores['player_id'].isin(active_player_ids)]
    .merge(target_game_weeks, left_on='game_week_id', right_on='id', how='inner')
    .merge(
        profiles[['id', 'username']],
        left_on='player_id',
        right_on='id',
        how='inner',
        suffixes=('', '_profile')
    )
)

# Keep relevant columns
df = merged[['username', 'week_number', 'points', 'correct_scores']].copy()

print(f"Target season: {target_season_id}")
print(f"Data shape: {df.shape}")
print(f"Weeks: {sorted(df['week_number'].unique())}")
print(f"Players: {len(df['username'].unique())}")
df.head()

Target season: f010783f-7fb5-40d8-9e00-6d8a45fa448e
Data shape: (220, 4)
Weeks: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Players: 44

      username  week_number  points  correct_scores
0  Rod McGeady            2       4               0
1      Parish             3       7               1
2       Donna             5       3               0
3  Rod McGeady            5       3               0
4         Si B            3       6               1

In [12]:
# Calculate cumulative points and correct scores for each player per week
# Remove missing usernames and duplicate player/week entries before ranking

df = df.dropna(subset=['username']).copy()
df = df[df['username'] != 'Martinez'].copy()

df = (
    df.groupby(['username', 'week_number'], as_index=False)
      .agg(points=('points', 'sum'), correct_scores=('correct_scores', 'sum'))
)

df_sorted = df.sort_values(['username', 'week_number']).copy()

df_sorted['cumulative_points'] = df_sorted.groupby('username')['points'].cumsum()
df_sorted['cumulative_correct_scores'] = df_sorted.groupby('username')['correct_scores'].cumsum()

# For each week, calculate league position
league_positions = []
for _, week_df in df_sorted.groupby('week_number', sort=True):
    week_df = week_df.sort_values(
        ['cumulative_points', 'cumulative_correct_scores', 'username'],
        ascending=[False, False, True]
    ).copy()
    week_df['position'] = range(1, len(week_df) + 1)
    league_positions.append(week_df)

league_positions = pd.concat(league_positions, ignore_index=False)

# Pivot to get position by week for each player
position_by_week = league_positions.pivot(index='username', columns='week_number', values='position')

print('League positions by week:')
print(position_by_week.head())
position_by_week

League positions by week:
week_number        1   2   3   4   5
username
Alan Taylor-Reed  13  16   7  11  16
Bincho            10  17   2   2   3
Bob sullivan       1   9  29  22  29
Bryan             27  25  15  13  24
CFC Stew           6  14  31  33  23

week_number        1   2   3   4   5
username
Alan Taylor-Reed  13  16   7  11  16
Bincho            10  17   2   2   3
Bob sullivan       1   9  29  22  29
Bryan             27  25  15  13  24
CFC Stew           6  14  31  33  23
Canada Steve      18  35  27  20  17
Chris Guyatt      19  18   6   7   6
Chris Torode      44  44  44  42  41
Dan Eagles        40  32  35  40  25
Des McCarthy      41  27  24  19  30
Donna             28  26  28  14  18
Gerard            12  20   8  15  19
Gerry McCarthy    34  31  22  25  27
Graham Dongworth  14   6  25  23  31
Hurricane         38  39  42  44  44
Ian               42  40  34  34  32
Jack Massie        7  21  26  35  38
Jim Shirley        8   3  11  17  12
KAV               20  28  30  32  20
Lenny Wright      17  15  32  26   9
Liam Okeeffe      39  43  40  36  33
Martin H          36  41  43  39  40
MattyCdogg        15  10  16  21  14
Mel                2   7   4   3   2
Mjd-⚒️⚒️⚒️        21  33  41  43  43
Murphty           29  22   3   1   1
Neil Morgan       22  11  17  16  15
Nick Arnold       23  29  39  37  34
NickBurchall      24   8  14  12  11
Parish            16   1   1   6   7
Paul and Janine    3  19  18  27  36
Phil Huffer        4  12  19  28  37
Poodle             9   4   9   5   4
Rod McGeady       30  36  38  41  42
Roger Rouse       25  23  12   9  10
RogerStanton      43  24   5   8   8
Si B               5  13  20  30  26
Stephen O         31  34  33  38  35
Steve arnold      32  42  36  29  39
SteveJos          33  30  21  24  21
The General       26  37  23  18  22
Tom D             37  38  37  31  28
big k             35   5  10   4   5
🍺The Barman       11   2  13  10  13

In [13]:
# Create interactive line chart with Plotly
fig = go.Figure()

# Define bright neon colors for lines
neon_colors = [
    '#FF00FF', '#00FFFF', '#00FF00', '#FFFF00', '#FF0080', 
    '#80FF00', '#0080FF', '#FF8000', '#FF0040', '#40FF00',
    '#00FF80', '#8000FF', '#FF0000', '#00FF40', '#4000FF',
    '#FF4000', '#00FFFF', '#FF00BF', '#BFFF00', '#00BFFF',
    '#FF00FF', '#00FF00', '#FFBF00', '#BF00FF', '#00FFBF',
    '#FF80FF', '#80FFFF', '#FFFF80', '#FF80C0', '#C0FF80',
    '#80C0FF', '#FFC080', '#C080FF', '#80FFC0'
]

# Get sorted player names (alphabetically)
players = sorted(position_by_week.index)

# Add a line for each player (start with all hidden)
for idx, player in enumerate(players):
    player_positions = position_by_week.loc[player]
    weeks = player_positions.index.tolist()
    positions = player_positions.values.tolist()
    
    fig.add_trace(go.Scatter(
        x=weeks,
        y=positions,
        mode='lines+markers',
        name=player,
        line=dict(width=2.5, color=neon_colors[idx % len(neon_colors)]),
        marker=dict(size=7, color=neon_colors[idx % len(neon_colors)]),
        visible='legendonly'
    ))

# Update layout with dark theme
fig.update_layout(
    title=dict(
        text='League Position Progression Throughout the Season',
        font=dict(color='#E0E0E0', size=18)
    ),
    xaxis_title='Game Week',
    yaxis_title='League Position',
    yaxis=dict(
        autorange='reversed',
        range=[0, 35],
        dtick=5,
        gridcolor='#404040',
        color='#E0E0E0',
        zeroline=False,
        showline=False,
        mirror=False,  # Don't mirror axis on opposite side
        fixedrange=True  # Disable zoom/pan on y-axis
    ),
    xaxis=dict(
        dtick=1,
        gridcolor='#404040',
        color='#E0E0E0',
        range=[0, len(position_by_week.columns) + 1],
        showline=False,  # Hide the x-axis line
        fixedrange=True  # Disable zoom/pan on x-axis
    ),
    plot_bgcolor='#1A1A1A',
    paper_bgcolor='#000000',
    font=dict(color='#C0C0C0'),
    hovermode='closest',
    dragmode=False,  # Disable dragging/panning
    legend=dict(
        title=dict(text='Players (click to toggle)', font=dict(color='#E0E0E0')),
        yanchor='top',
        y=1,
        xanchor='left',
        x=1.02,
        bgcolor='rgba(0,0,0,0.7)',
        bordercolor='#404040',
        borderwidth=1,
        font=dict(color='#C0C0C0')
    ),
    height=600,
    showlegend=True,
    updatemenus=[
        dict(
            type='buttons',
            direction='left',
            buttons=[
                dict(
                    label='Show All',
                    method='update',
                    args=[{'visible': True}]
                ),
                dict(
                    label='Hide All',
                    method='update',
                    args=[{'visible': 'legendonly'}]
                )
            ],
            x=1.0,
            xanchor='right',
            y=1.15,
            yanchor='top',
            bgcolor='#2A2A2A',
            bordercolor='#404040',
            font=dict(color='#000000')  # Black text for better contrast on white active state
        )
    ]
)

fig.show()

## Export Chart

In [14]:
from datetime import datetime

# Generate filename with today's date (DDMMYY format)
date_str = datetime.now().strftime('%d%m%y')
filename = f'LeagueProgression{date_str}.html'
filepath = f'../Output/{filename}'

# Export to Output directory
fig.write_html(filepath)
print(f"✓ Chart exported to: {filepath}")

✓ Chart exported to: ../Output/LeagueProgression240926.html